AWX:
  # enable use of awx-deploy template
  enabled: false
  name: awx
  spec:
    admin_user: admin
    projects_persistence: true
    projects_storage_size: 50Gi
    projects_storage_access_mode: ReadWriteMany

  # configurations for external postgres instance
  postgres:
    enabled: false
    host: Unset
    port: 5678
    dbName: Unset
    username: admin
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Unset
    sslmode: prefer
    type: unmanaged
